### ISSUE TITLE
Investigar reconocimiento de objetos 

### ISSUE THREAD

**Issue by Javi96** [Javi96/TMI#19]
Investigar tecnologías para reconocer entidades dentro de una imagen. Probar tecnologías a ver que tal sale

**Comment by Aitorcay** [comment]
Branches a revisar: textrazor y dandelion.
Dandelion: extracción de entidades relacionadas con comida.
TextRazor: más orientada a procesado de texto. Enfocada hacia la extracción de grupos nominales y expresiones temporales.
