### ISSUE TITLE
Definir modelos de datos

### ISSUE THREAD

**Issue by Dani-Basta** [Javi96/TMI#23]
Definir qué tipo de modelo de datos tendrá cada elemento.

**Comment by Aitorcay** [comment]
Comenzaremos por el almacenamiento de ingredientes para elaborar un inventario del usuario.
Para cada ingrediente se almacenará un nombre, una cantidad y una unidad de medida.

**Comment by Javi96** [comment]
El modelo es correcto y se ha integrado en la app. No obstante es posible que cambie en breve
