### ISSUE TITLE
Tecnologías empleadas

### ISSUE THREAD

**Issue by Dani-Basta** [Javi96/TMI#6]
Resumen y justificación de las tecnologías usadas para el desarrollo.

**Comment by Dani-Basta** [comment]
En la API de Text Recognition: la última linea de alimentos etiquetados, entiendo que se refiere a luego combinar reconocimiento de imágenes y de texto para extraer más información. ¿Esto cuándo se ha comentado?
En el apartado de CoreNLP: los 2 ejemplos no me parecen para nada ilustrativos, además de que están en inglés. Y en cuanto a la imagen me parece que no termina de ser suficientemente ilustrativa.

**Comment by Aitorcay** [comment]
Lo de los alimentos etiquetados iba por cuando comentamos las cosas tipo "lata de atún" o "leche".
He encontrado la parte de español del CoreNLP. Cambio los ejemplos por una tabla con lo específico que podríamos utilizar.

**Comment by Javi96** [comment]
Se cierra la issue, ya está el merge
